#!/bin/sh
grep -h message: commit*.yml |

tr -cs A-Za-z\' '\n' |
# Replace nonletters with newlines

tr A-Z a-z |
#Map uppercase to lowercase

sort |
#Sort the words in ascending order

uniq -c |
#Eliminate duplicates, showing their counts

sort -k1,1nr -k2 |
#Sort by descending count, and then by ascending word
less
